mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
        - "./mysql/init:/docker-entrypoint-initdb.d"
        - "./mysql_study:/mysql_study"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
        - 3306:3306
